### ISSUE TITLE
timings in header followed by a blank line is not parsed correctly

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#224]
https://w3c.github.io/webvtt/#file-parsing

> If the character indicated by position is a U+000A LINE FEED (LF) character, advance position to the next character in input.

Consider this file:

```
WEBVTT
00:00:00.000 --> 00:00:01.000

Test
```

This parses into a cue with cue text "Test" per spec, AFAICT. This looks like a bug.

Metadata header loop
> 14 The character indicated by position is a U+000A LINE FEED (LF) character. Advance position to the next character in input.

> 15 If line contains the three-character substring "-->" (U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS, U+003E GREATER-THAN SIGN), then set the already collected line flag and jump to the step labeled cue loop.

Now position is at the blank line.

> 17 Cue loop: If the already collected line flag is set, then jump to the step labeled cue creation.

Cue creation:

> 22 If line contains the three-character substring "-->" (U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS, U+003E GREATER-THAN SIGN), then jump to the step labeled timings below.

> 28 Timings: Unset the already collected line flag.

> 29 Collect WebVTT cue timings and settings from line using regions for cue. If that fails, jump to the step labeled bad cue.

didn't fail...

> 31 Cue text loop: If position is past the end of input, then jump to the step labeled cue text processing.

> 32 If the character indicated by position is a U+000A LINE FEED (LF) character, advance position to the next character in input.

This is the bug. This skips past the blank line so position is at the start of the "Test" line.

**Comment by silviapfeiffer** [comment]
From my reading: 15 doesn't include reading the newline, but only the content in the line.

**Comment by zcorpan** [comment]
Step 14 consumes the newline. Step 15 checks what line contains. That line was actually consumed earlier (step 10).

**Comment by silviapfeiffer** [comment]
Hmm looks like you're right. 32 is surplus.

**Comment by zcorpan** [comment]
In this particular case yes. In the valid case, dropping that step seems to drop the cue identifier. I don't plan on figuring out how to fix this bug with the current spec algorithm; instead I intend to specify the new algorithm which doesn't have this bug.
