### ISSUE TITLE
Clarify that <b> can use a class name and CSS

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#228]
https://w3c.github.io/webvtt/#webvtt-bold-object

> WebVTT Bold Objects

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=28262

Also http://www.w3.org/International/questions/qa-b-and-i-tags (the Japanese example)

For HTML @r12a said that the way to handle this example in HTML is to use span or b with a class name, and use CSS to style it differently for different languages. So we should clarify that this is possible in WebVTT as well and add an example of how to do that for this in particular.

**Comment by r12a** [comment]
:+1:
