### ISSUE TITLE
"parse a percentage string" parses ".1%" and "1.%"

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#233]
https://w3c.github.io/webvtt/#parse-a-percentage-string

> parse a percentage string

This algorithm doesn't fail for the strings  ".1%" and "1.%". Is that intentional? I think it should fail if it doesn't match https://w3c.github.io/webvtt/#webvtt-percentage

**Comment by silviapfeiffer** [comment]
Yeah that was intentional to be a boot more generous in what we accept.

**Comment by zcorpan** [comment]
Hmm OK, bit it's not consistent with HTML or CSS, which seems bad.

**Comment by foolip** [comment]
".1%" works in CSS, but "1.%" doesn't. Aligning with that in both syntax (why require a leading 0?) and parsing seems OK.

**Comment by silviapfeiffer** [comment]
agree with foolip

**Comment by zcorpan** [comment]
HTML requires a leading 0 (for both syntax and parsing). But I could live with having leading zero be optional I suppose.

https://html.spec.whatwg.org/multipage/infrastructure.html#percentages-and-dimensions

**Comment by foolip** [comment]
If you'd like that better you'll get no objection for me, as far as consistency is concerned I'd value consistency with HTML over CSS.

**Comment by silviapfeiffer** [comment]
Grumble... Why can't CSS and html be consistent... Either works for me in this case!

**Comment by dwsinger** [comment]
> On Nov 2, 2015, at 6:47 , Silvia Pfeiffer <notifications@github.com> wrote:
> 
> Grumble... Why can't CSS and html be consistent... Either works for me in this case!

yes.  so maybe we should be consistent with our past and existing files?  

> 
> —
> Reply to this email directly or view it on GitHub.
> 

David Singer
Manager, Software Standards, Apple Inc.
