### ISSUE TITLE
Ruby text has no background by default

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#234]
https://w3c.github.io/webvtt/#applying-css-properties

> The background shorthand property on the WebVTT cue background box must be set to 'rgba(0,0,0,0.8)'. [CSS3-COLOR]

https://zcorpan.github.io/live-webvtt-viewer/#vtt=WEBVTT%0A%0A00%3A00%3A00.000+--%3E+00%3A00%3A10.000%0A%3Cruby%3Efoo%3Crt%3Ebar%3C%2Fruby%3E%0A

Check in Firefox. The ruby text is white on white background. Maybe `<rt>` should have a default background also.

**Comment by zcorpan** [comment]
http://software.hixie.ch/utilities/js/live-dom-viewer/saved/3735 shows the visual difference with HTML.

**Comment by zcorpan** [comment]
cc @eric-carlson @rickeyre

**Comment by foolip** [comment]
I'm thinking that people would probably expect a single box the fits all of the text...

**Comment by zcorpan** [comment]
So use a block background box by default? (Related: #249)
