### ISSUE TITLE
Add default styling to "well-known" classes

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#270]
See https://github.com/w3c/webvtt/pull/261#issuecomment-157855519

I think the default rendering should be the same in all user agents, but I don't really mind having a simple default stylesheet for webvtt with some classes like "red".

One problem is if we want to support changing the background color of the background box, we probably have to add a way to specify classes on cues.

This would actually be backwards compatible syntax if we need classes on cues:

```
WEBVTT

00:00:00.000 --> 00:00:10.000.foo.bar align:start
Hello world.
```

**Comment by zcorpan** [comment]
Also see comments in #272

**Comment by zcorpan** [comment]
See https://github.com/w3c/webvtt/issues/272#issuecomment-161910184

If we continue the assumption that there will be VTT implementations that don't have CSS support, it appears that, from the above comment:

* We don't need a way to change the background color from the default `rgba(0,0,0,0.8)`, which is black with 20% transparency. If some users need opaque background, that seems better as a user setting, since it will then affect all subtitles.
* We only need to support a handful of foreground colors: white (default), yellow, cyan, red, magenta, green (`lime` in CSS).
* CEA608 also has blue and black text colors, but they are dark so will not be very accessible on a black background, and apparently they are not a requirement. I suggest we don't support them.
* Other features like font-size, text-shadow, etc. are not a requirement.

**Comment by silviapfeiffer** [comment]
I'd ask Ken about whether blue and black should be supported. Some videos have a predominantly white color and then a dark text color is useful. Also, I think it would be useful to stay compatible with cea608 on this. But do ask Ken.

**Comment by silviapfeiffer** [comment]
@loretta may be helpful with the summoning ;-)

**Comment by zcorpan** [comment]
> Some videos have a predominantly white color and then a dark text color is useful.

WebVTT cues have a default background of `rgba(0,0,0,0.8)`, which is dark regardless of what the video is. The brightest it can be is \#333333, in case the video is all-white. Blue and black text on \#333333 is not enough contrast per http://webaim.org/resources/contrastchecker/


The "darkest" blue that is at least 4.5:1 contrast is [\#8f8fff](http://webaim.org/resources/contrastchecker/?fcolor=8f8fff&bcolor=333333). Is it OK to map .blue to that? Should we change the other colors as well?

Red is also not enough, btw. [\#ff6a6a](http://webaim.org/resources/contrastchecker/?fcolor=ff6a6a&bcolor=333333) is at least 4.5:1.

Supporting black just doesn't make sense if we don't also support customising or turning off the background.

**Comment by silviapfeiffer** [comment]
So, yes, cea708 allows change of background color and we tried to replicate that for webvtt: https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#cea-708-background-colour . There may be another bug somewhere for this.

**Comment by zcorpan** [comment]
Closing per https://github.com/w3c/webvtt/pull/279#issuecomment-273751072
