### ISSUE TITLE
kero19

### ISSUE THREAD

**Issue by kero19** [w3c/webvtt#281]
https://w3c.github.io/webvtt/#regions

**Comment by kero19** [comment]
4

**Comment by skynavga** [comment]
spam?

**Comment by silviapfeiffer** [comment]
yeah, not sure why I can't close it :-(

**Comment by skynavga** [comment]
I was trying to close it also, but couldn't. Let me ask PLH.

**Comment by nigelmegitt** [comment]
I can't seem to close any issue, and worse, ash-nazg isn't listing this repo any more, which is weird.

**Comment by zcorpan** [comment]
It's my fault you can't close issues, sorry. I wanted to prevent clicking on "merge" buttons (because I prefer linear git history, and the green button breaks that), but I don't mind others being able to close issues. I'll look into if the settings can be tweaked here...
