### ISSUE TITLE
Unicode normalization example is wrong

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#282]
https://w3c.github.io/webvtt/#example-11b9d845

> For example, a cue with the identifier consisting of the characters U\+0041 LATIN CAPITAL LETTER A and U\+212B ANGSTROM SIGN will not match a selector targeting a cue with an ID consisting of the character U\+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE\.

Remove `s U+0041 LATIN CAPITAL LETTER A and`. Angstrom is not a combining character...

cc @r12a

**Comment by aphillips** [comment]
There are three strings that would make "normalization friends" for U+00C5. These are:

> U+00C5 LATIN CAPITAL LETTER A WITH RING ABOVE (a precoposed character)
> U+212B ANGSTROM SIGN (a compatibility character)
> U+0041 U+030A LATIN CAPITAL LETTER A followed by COMBINING RING ABOVE (a decomposed character sequence)

These should be the examples, assuming you use A-ring.

**Comment by aphillips** [comment]
Change looked good to me.
