### ISSUE TITLE
After overlap resolution, new cue positions should be represented in the DOM

### ISSUE THREAD

**Issue by rgov** [w3c/webvtt#285]
From [WebKit bug 154241](https://bugs.webkit.org/show_bug.cgi?id=154241):

After cues have been moved around in order to resolve overlapping boxes, the new cue positions should be exposed in the DOM. Otherwise the top and left of the cue elements do not match reality.

**Comment by zcorpan** [comment]
Rendering in the spec is not defined in terms of DOM. Possibly it should be, but right now it's not.

**Comment by silviapfeiffer** [comment]
You talk about testing in the WebKit bug. What kind of testing are you
after? Browser tests? If not, what is your user case?

Best Regards,
Silvia.

**Comment by zcorpan** [comment]
There is nothing to fix in the spec for this issue without first revamping the whole rendering section to be defined in terms of a DOM instead of custom objects. Closing.
