### ISSUE TITLE
The description is no difference between the "start alignment" and "end alignment" in text alignment

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#287]
https://w3c.github.io/webvtt/#cues

> The text of each line is individually aligned towards the start side of the box, where the start side for that line is determined by using the CSS rules for plaintext value of the unicode\-bidi property\. 

Is that mean "end side"? 
It's totally the same description for "start alignment" and "end alignment".

**Comment by zcorpan** [comment]
Thank you!
