### ISSUE TITLE
Error enum value for "position-align"

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#288]
https://w3c.github.io/webvtt/#enumdef-positionalignsetting

These value are not consistent with the description in #dom-vttcue-positionalign.
In description, it said the value should be "line-left", "center", "line-right", "auto".

**Comment by zcorpan** [comment]
Thank you!

**Comment by smaug----** [comment]
So this is backwards incompatible change. There are implementations which had the webidl following spec's webidl, and that now was changed. Was that intentional?

**Comment by smaug----** [comment]
but it would have been safer to change the prose to follow webidl. Is there a reason to not do that?

**Comment by smaug----** [comment]
though, I guess we'll just update Gecko.

**Comment by zcorpan** [comment]
If there is too much content relying on the old values then we should revert it in the syntax also, not just in IDL. But this feature is not widely implemented yet I believe.
