### ISSUE TITLE
Wrong description for computing "x/y-position"

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#290]
https://w3c.github.io/webvtt/#processing-model

> If the WebVTT cue snap\-to\-lines flag is set, then run the appropriate steps from the following list:​

If I understand correctly, the y-position should be computed when the WebVTT cue's writing direction is horizontal, and x-position for the vertical writing direction.

Think about that, we set y-position be 0 in above step 6, and said it's "temporary positions used to calculate box dimensions below." However, we still set the x-position in following steps, so that the y-position still be zero and it seems like a serious error.

**Comment by zcorpan** [comment]
Huh, yes, I believe you're right. Step 7 has x/y backwards. Good catch!

**Comment by zcorpan** [comment]
Hmm, no, wait, I think it's correct. Step 7 adjusts the position and size in the "inline" direction when snap-to-lines is set. Step 11 then moves boxes in the other dimension.

**Comment by alastor0325** [comment]
Hi, @zcorpan,
Sorry for my delay reply.

I still think that's incorrect, let me explain.

First, step 8 is the ONLY place to set the CSS attribute "left" and "top", and these value are depend on the "x-position" and "y-position". That means we must calculate them before this step.

Then, see step8,
>  "Apply the terms of the CSS specifications to nodes "

If you don't set the "left" and "top" before this step, the node would not get the correct CSS specifications.

Therefore, before step11, the box should be moved to the initial position, and then adjust their position to avoid overlapping in step 11.

How do you think?
Thanks!

**Comment by zcorpan** [comment]
Step 11 doesn't only do overlap avoidance, it also places the lines according to their computed line when snap-to-lines is true. So for horizontal a cue is "top: 0" and then step 11 moves things around.

**Comment by alastor0325** [comment]
Ah...I think I got it!
Thanks again :)
