### ISSUE TITLE
Missing label [CSS-VALUES]

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#295]
https://w3c.github.io/webvtt/#ref-for-webvtt-region-anchor-4

> Let left be leftOffset subtracted from 'viewportAnchorX vw'
> Let top be topOffset subtracted from 'viewportAnchorY vh'.

Do we miss the label **[CSS-VALUES]** for "left" and "top"? Or they're not related with the CSS attributes here?
Thanks!

**Comment by zcorpan** [comment]
They are just variables here, and used in the following section 'Applying CSS properties to WebVTT Node Objects'.

**Comment by alastor0325** [comment]
It seems I misunderstood the meaning of this label, I previously thought that we need the label if this property is CSS related .
Thanks!
