### ISSUE TITLE
Default value for "line" and "position"

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#300]
https://w3c.github.io/webvtt/#cues

Hi, could you help me verify the default value of these two attributes?

1. line :  "auto" for default value? or...? (because I don't see the clear description in "computed line")
2. position : 50% for default value?

Thanks!

**Comment by zcorpan** [comment]
The default is auto for both, which computes to something as defined. I've tried to make this clearer in #302, please take a look.

**Comment by alastor0325** [comment]
Thanks you!
