### ISSUE TITLE
Parsing question about "line terminators"

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#303]
https://w3c.github.io/webvtt/#file-structure

> step 6. One or more WebVTT line terminators to terminate the header block and separate the cues from the file header. 

If we don't have any meta data header in step5, why we still need one more "line terminators" to separate the cues and header?

In addition, the meta data header already contains one "line terminators [1], so I think the step 6 might be changed to "Zero or more WebVTT line terminators"?

The reason I ask this question is because I want to verify whether this vtt file [2] is correct, since this one only has one "line terminators" after "WEBVTT".

Thanks!

[1] https://w3c.github.io/webvtt/#webvtt-metadata-header
[2] http://w3c-test.org/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/header-timings.vtt

**Comment by zcorpan** [comment]
The section you link to is defining the syntax for how to *write* a *valid* VTT file. It does not at all cover how to parse it. Parsing is defined in https://w3c.github.io/webvtt/#parsing

Currently there are no defined metadata headers. "Region" used to be one but we changed it to be a block instead. So in the syntax the spec could remove step 5 entirely. But the intent is that there should be a blank line before the first cue and between cues in valid files.

That file is parsed as follows:

* Steps 1..9 skip over the first line.
* Step 10 invokes "collect a WebVTT block" with the *in header* flag set. It collects the second line, then 11.4 of that algorithm:
 
 > If line contains the three-character substring "-->" (U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS, U+003E GREATER-THAN SIGN), then run these substeps:
 
 then *in header* is set, so
 
 > Otherwise, let position be previous position and break out of loop.
 
 and it then returns null.
* Back to the main parser, *position* is now at the start of the second line. Step 11 skips over zero LF chars.
* Step 13 parses a single cue.

(It's possible that some of the tests are out of date with the current spec; if you find bugs in the tests please file at w3c/web-platform-tests and cc me. 🙂)

**Comment by alastor0325** [comment]
Thanks! I'll check the parsing algorithm again!

But I have one more question about "header-timings.vtt", because it doesn't contain the "line terminator" after the "{}", is it a correct cues text block?

Actually, I already have found some web-platform-tests don't follow the current spec. eg. the default value of line and position in 001.html [1]. Now I would modify them on Gecko first, and then send the PR to w3c/web-platform-tests/webvtt :)

[1] https://github.com/w3c/web-platform-tests/blob/master/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/001.html

**Comment by alastor0325** [comment]
Just want to make sure again,

> But the intent is that there should be a blank line before the first cue and between cues in valid files.

From your reply, the step6 is used to generate a blank line separate the signature and cues. Therefore, the "header-timings.vtt" is wrong because it doesn't have a blank line, is that right?

**Comment by zcorpan** [comment]
That file is invalid, sure. But it is intentionally testing that case, so as a test it isn't wrong.

Yes, the syntax requires a linebreak and the end of a cue block. Maybe we should change that to allow EOF without the linebreak at the end?

**Comment by alastor0325** [comment]
> That file is invalid, sure. But it is intentionally testing that case, so as a test it isn't wrong.

Error is here [1], this file indicates that the "header-timings.vtt" and "header-space.vtt" should have one cue.

[1] http://w3c-test.org/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/cue-counts.json

> Yes, the syntax requires a linebreak and the end of a cue block. Maybe we should change that to allow EOF without the linebreak at the end?

It sounds good to me :)

**Comment by zcorpan** [comment]
It *should* have one cue per spec, as I noted in [the comment above](https://github.com/w3c/webvtt/issues/303#issuecomment-227374585). :-)

**Comment by silviapfeiffer** [comment]
There are several bugs in the bug tracker still about other types of headers. Do if we decide at a later stage to actually add those, will we change the rules back?

**Comment by zcorpan** [comment]
Yes.

**Comment by alastor0325** [comment]
It seems little tricky, if the vtt file is invalid, why it can be parsed to valid cue?
Maybe we should remove the constraint that needs to have a blank line between signature and cues block?

**Comment by zcorpan** [comment]
https://w3c.github.io/webvtt/#conformance-classes discusses this exact case. In short, there is no 1:1 relationship between what is allowed in the syntax and what the parser creates objects for. The situation is the same in HTML.

**Comment by zcorpan** [comment]
There was no technical error in the spec here, from what I can tell, so closing. Please comment if I missed something or if you have a proposal to make the spec clearer. Thanks!
