### ISSUE TITLE
Question about the definition for metadata header

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#304]
https://w3c.github.io/webvtt/#webvtt-metadata-header

> A WebVTT metadata header name and a WebVTT metadata header value each consist of any sequence of one or more characters other than U+000A LINE FEED (LF) characters and U+000D CARRIAGE RETURN (CR) characters

If the header name and the header value can contain any characters other than LF and CR, that means the ":" can be contained in theses property.

If so, this kind of description would be allowed for metadata header, eg: foo:foo:foo:foo:foo:foo:foo. However, how can we know which colon is used for separate name and value? Maybe we should not allow containing colon in both metadata name and value.

Thanks!

**Comment by zcorpan** [comment]
We should just remove metadata syntax since it's not currently used...

**Comment by alastor0325** [comment]
Just FYI, the reason I ask this question is because I saw this article [1] mention the usage of the metadata header.
[1] http://wiki.webmproject.org/webm-metadata/temporal-metadata/webvtt-metadata

**Comment by zcorpan** [comment]
OK thx. Those headers have never been part of the spec though.

**Comment by silviapfeiffer** [comment]
https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html was the motivation for those. Meta data headers are ignored in browsers but used other places.

**Comment by bdougherty** [comment]
It doesn't seem to be required, but the HLS spec defines using a metadata header for VTT https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-3.5
