### ISSUE TITLE
Fix non-integer values for line setting

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#306]
From https://github.com/w3c/web-platform-tests/issues/3222#issuecomment-227681157

It is possible with the DOM API to set `line` to `1.5` and have `snapToLines` be true, but the spec doesn't say what to do with it. Should it round the value? Floor? Treat as "auto"?

Note that the parser will drop a `line:1.5` setting.

**Comment by fsoder** [comment]
Isn't this covered by the rendering steps:

> Round line to an integer by adding 0.5 and then flooring it.

https://w3c.github.io/webvtt/#apply-webvtt-cue-settings (11.7 w/ snap-to-lines true)

**Comment by zcorpan** [comment]
Hmm yes, you're right. I somehow missed that. Thanks!
