### ISSUE TITLE
Question about the parsing cue's timestamp

### ISSUE THREAD

**Issue by alastor0325** [w3c/webvtt#311]
https://w3c.github.io/webvtt/#collect-a-webvtt-timestamp

Hi, @zcorpan,
I have some questions about timestamp parsing.

### 1. Characters showing before or after the timestamp?
In the step4 of the **collect a WebVTT timestamp**, it mentions,
> If the character indicated by position is not an ASCII digit, then return an error and abort these steps.

Does that mean we can't add any characters (except LF and CRLF) **before** start time?
However, in [space-chars.vtt](http://w3c-test.org/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/space-chars.vtt), it allows to have characters **before** timestamp.

In addition,  I didn't see any constraint about adding the characters **after** end time.
However, in [space-chars.vtt](http://w3c-test.org/webvtt/webvtt-file-format-parsing/webvtt-file-parsing/support/space-chars.vtt), the last case doesn't allow to have vertical tabs **after** timestamp.

Could you help me to explain them :) ?

### 2. start time and end time
Do we need to check whether the start time and the end time are both valid in the parsing step? eg. the start time is later than the end time. Or we would throw error in next steps like rendering steps or something else?

Thanks!

**Comment by zcorpan** [comment]
1
---

https://w3c.github.io/webvtt/#cue-timings-and-settings-parsing

step 3 skips leading whitespace on the line.
->
https://html.spec.whatwg.org/multipage/infrastructure.html#skip-whitespace
->
https://html.spec.whatwg.org/multipage/infrastructure.html#space-character
> U+0020 SPACE, U+0009 CHARACTER TABULATION (tab), U+000A LINE FEED (LF), U+000C FORM FEED (FF), and U+000D CARRIAGE RETURN (CR)

So vertical tab is not a "space character".

2
---
No.

https://html.spec.whatwg.org/multipage/embedded-content.html#time-marches-on step 1 checks the start time and end time; if end time is less then start time then the cue will just never be in *current cues* in that algorithm.

**Comment by alastor0325** [comment]
Very appreciate your explanation :)
