### ISSUE TITLE
Inconsistent VTTRegion API Definitions

### ISSUE THREAD

**Issue by BenjaminSchaaf** [w3c/webvtt#329]
For [VTTRegion](https://w3c.github.io/webvtt/#the-vttregion-interface): `width`, `regionAnchorX`, `regionAnchorY`, `viewportAnchorX` and `viewportAnchorY` describe setting with a value "interpreted as a percentage" for their detailed description. However in the overview definition it states it should throw a `IndexSizeError` if outside the 0..100 range.

This is inconsistent with the API definitions for `VTTCue`

**Comment by zcorpan** [comment]
It seems Chromium and WebKit throw for values outside the range. Gecko does not support `VTTRegion`.

http://software.hixie.ch/utilities/js/live-dom-viewer/saved/4900
