### ISSUE TITLE
Setting VTTRegion.lines to a negative value should throw

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#333]
http://w3c.github.io/webvtt/#the-vttregion-interface

> The lines attribute, on getting, must return the WebVTT region lines of the WebVTT region that the VTTRegion object represents\. On setting, the WebVTT region lines must be set to the new value\.

Test: http://w3c-test.org/webvtt/api/VTTRegion/lines.html

In Chrome 58.0.3020.0 canary (which has this fix https://bugs.chromium.org/p/chromium/issues/detail?id=690014#c3 ) this throws IndexSizeError if value is < 0.

https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/html/track/vtt/VTTRegion.cpp?l=111&rcl=861e1e50380132d7028812bba3f3d4f073fa4c26

The syntax does not support negative values, so it would be sensible to throw for negative values. I suggest we change the spec and test to match Chromium implementation.

cc @fsoder @BenjaminSchaaf

**Comment by BenjaminSchaaf** [comment]
Then I'd also suggest changing the parser to ignore `lines` for values < 0

https://w3c.github.io/webvtt/#region-settings-parsing

**Comment by zcorpan** [comment]
It already does.

> If value contains any characters other than ASCII digits, then jump to the step labeled next setting.
