### ISSUE TITLE
Parsing: should drop line:100,invalid setting

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#336]
http://w3c.github.io/webvtt/#cue-timings-and-settings-parsing

> Let cue’s WebVTT cue line be number\.
> 
> If the last character in linepos is a U\+0025 PERCENT SIGN character \(%\), then let cue’s WebVTT cue snap\-to\-lines flag be false\. Otherwise, let it be true\.

I think we should validate `linealign` before setting the WebVTT cue line. Equivalent for position setting. It is bad for future extensibility to use the line/position with unrecognized alignment.

(Noticed this when looking at @BenjaminSchaaf's revamp of parsing tests.)

**Comment by silviapfeiffer** [comment]
They are just numbers at this stage, not interpreted into actual positions. Why would it matter?

**Comment by zcorpan** [comment]
The normal parsing of settings in WebVTT is to drop it on the floor if there is a syntax error. This case does not do that.

It matters because it gives unexpected result and makes it difficult to start using new alignments in the transition period when some implementations support the new value and some do not.

Let's say browsers implement what the spec requires now. Then we add a new alignment "foo". Then the author uses it like this, providing a fallback for legacy UAs:

```
00:00:00.000 --> 00:00:10.000 line:50% line:25%,foo
Test
```

The expectation is that legacy UAs use the first setting and ignore `line:25%,foo`, and new UAs apply the second setting because they support `foo`. With the current spec legacy UAs would apply `line:25%` and ignore `,foo`. This is bad.

**Comment by silviapfeiffer** [comment]
Ah yeah that makes sense. Good find!
