### ISSUE TITLE
Recursively disallow external resources

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#341]
http://w3c.github.io/webvtt/#style-no-external-resources

> For the purpose of resolving URLs in STYLE blocks of a WebVTT file, if the URL’s scheme is not "data", then the user agent must act as if the URL failed to resolve\.

Need to disallow external resources (other than `data:`) within `@import`ed `data:` URL stylesheets or SVG images as well.

```
STYLE
::cue(#x) { background-image: url("data:image/svg+xml,<svg ...><image xlink:href='https://example.org/'/></svg>"); }
```

**Comment by nigelmegitt** [comment]
Why prevent SVG images from loading?

**Comment by zcorpan** [comment]
The SVG image itself should load if the URL to the image is a `data:` URL. But for privacy reasons WebVTT (or the HTML `video`/`track` elements more generally in HTML UAs) need to not be able to reference external resources. The WebVTT spec already disallows external resources to be fetched when found in `STYLE` blocks, but not when found inside an SVG image inside a `STYLE` block.

**Comment by nigelmegitt** [comment]
Thanks @zcorpan I'm still a bit confused about this though. It seems inconsistent to say that for privacy reasons a URL must not be loaded but then also say it _should_ be loaded if it is a `data:` URL. Why would the URL scheme affect the privacy impact? They seem orthogonal at least on first glance.

**Comment by zcorpan** [comment]
`data:` includes all information in the URL itself; it will not connect to a remote server upon fetching. The privacy concern is about notifying a third party when the user views a video with some subtitles.

**Comment by nigelmegitt** [comment]
Ok thanks for the explanation - I'd forgotten about those weird `data:` URLs that are not locators but are in fact the data themselves.
