### ISSUE TITLE
Need tests for :cue-region(id) pseudo-class

### ISSUE THREAD

**Issue by zcorpan** [w3c/webvtt#355]
Introduced in https://github.com/w3c/webvtt/pull/349 , `:cue-region(id)` pseudo-class needs tests in web-platform-tests and then filing bugs asking to implement. Filing here to track the status.

**Comment by silviapfeiffer** [comment]
@BenjaminSchaaf are you able to add a test?

**Comment by BenjaminSchaaf** [comment]
Those test are already in this pr: https://github.com/w3c/web-platform-tests/pull/6503

**Comment by silviapfeiffer** [comment]
Added info to the registered bugs on browsers for region, see:
https://bugs.chromium.org/p/chromium/issues/detail?id=755487
https://bugs.webkit.org/show_bug.cgi?id=168716
https://bugzilla.mozilla.org/show_bug.cgi?id=1338031
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11025636/

**Comment by silviapfeiffer** [comment]
Tests have landed, so closing.
