### ISSUE TITLE
Wide Review Comment 2017: Term "WebVTT cue settings list" defined twice

### ISSUE THREAD

**Issue by tairt** [w3c/webvtt#360]
The term `WebVTT cue settings list` is ambiguous because it is defined twice and with different grammars.

## Definition in different chapters

> ### Chapter 4.1

> A WebVTT cue settings list consist of a sequence of zero or more WebVTT cue settings in any order, separated from each other by one or more U+0020 SPACE characters or U+0009 CHARACTER TABULATION (tab) characters. Each setting consists of the following components, in the order given:

> 1. A WebVTT cue setting name. 
> 2. An optional U+003A COLON (colon) character. 
> 3. An optional WebVTT cue setting value. 

> A WebVTT cue setting name and a WebVTT cue setting value each consist of any sequence of one or more characters other than U+000A LINE FEED (LF) characters and - U+000D CARRIAGE RETURN (CR) characters except that the entire resulting string must not contain the substring "-->" (U+002D HYPHEN-MINUS, U+002D HYPHEN-MINUS, U+003E GREATER-THAN SIGN).

**AND**

>### Chapter 4.4

>A WebVTT cue settings list consists of zero or more of the following settings. Each setting must not be included more than once per WebVTT cue settings list.
>
>* A WebVTT vertical text cue setting. 
>* A WebVTT line cue setting. 
>* A WebVTT position cue setting. 
>* A WebVTT size cue setting. 
>* A WebVTT alignment cue setting. 
>* A WebVTT region cue setting. 

## Comment
Although the definition of Chapter 4.4 is compliant with the definition in Chapter 4.1 (it is a specialization of the common syntax), the term `WebVTT cue settings list` can only defined once. Otherwise it is not clear to which the term refers, e.g. in Chapter 4.1:

> A WebVTT cue block consists of the following components, in the given order:
>1. ... 
>2. ...
>3. Optionally, one or more U+0020 SPACE characters or U+0009 CHARACTER TABULATION (tab) characters followed by **a WebVTT cue settings list**.

**Comment by dwsinger** [comment]
Nice catch.  I think that 4.4 should say that the following cue settings are defined and can appear in a Cue Settings List.

**Comment by silviapfeiffer** [comment]
Only the term in chapter 4.1 is a definition. The other one is a reference to the first one and a specialisation for right this time given the currently specified WebVTT cue settings.

I'll propose a patch similar to what @dwsinger suggested.

**Comment by silviapfeiffer** [comment]
Could you please review?

**Comment by tairt** [comment]
Thanks for the change! I will review it!

**Comment by tairt** [comment]
I reviewed the change. It get's rid of the ambiguity and is a solution of the this issue. So: looks good to me. Thanks!
