### ISSUE TITLE
Wide Review Comment 2017:  Chapter location for defining WebVTT chapter title text

### ISSUE THREAD

**Issue by tairt** [w3c/webvtt#362]
The term `WebVTT chapter title text` is defined in the section `4.6. Types of WebVTT files`. This should go in chapter `4.2 Types of WebVTT cue payload` (e.g. as `4.2.3`).

**Comment by silviapfeiffer** [comment]
Please review.

**Comment by tairt** [comment]
Thanks for the change. I will review it!

**Comment by tairt** [comment]
Thanks! Works for me!

**Comment by silviapfeiffer** [comment]
Thanks! Much appreciated!
