### ISSUE TITLE
Wide Review Comment 2017: Term definition with empty content

### ISSUE THREAD

**Issue by tairt** [w3c/webvtt#364]
It is very confusing that multiple terms by definition may have no content at all. One example is the definition of WebVTT metadata text:

> WebVTT metadata text consists of any sequence of zero or more characters other than U+000A LINE FEED (LF) characters and U+000D CARRIAGE RETURN (CR) characters, each optionally separated from the next by a WebVTT line terminator. (In other words, any text that does not have two consecutive WebVTT line terminators and does not start or end with a WebVTT line terminator.)

This means that the empty string may also be WebVTT metadata text. Therefore three empty strings could be separated by WebVTT line terminator which results in two consecutive WebVTT line terminators.

To define terms in this way make them also effectivly optional in production rules where they are used.

**Comment by silviapfeiffer** [comment]
@tairt if you have any patch proposals to your issues, we'd appreciate the help

**Comment by silviapfeiffer** [comment]
I don't think this can be addressed. Why should we require that a metadata cue has a minimum of one character? Why would we disallow empty metadata cues? An empty file is still a file. An empty cue is still a cue. If we were to require a minimum of one character in a metadata cue, this would lead to making perfectly valid files invalid, just because an empty cue slipped in. I don't think that is desirable.

**Comment by silviapfeiffer** [comment]
FYI: Following https://www.w3.org/wiki/TimedText/WebVTT_Wide_Review#Guidelines_for_Status_of_comments , the CG processing resolution is:

2.7- Done but comment Rejected

And the classification of the issue is:
c- substantive
since it would make certain files unnecessarily invalid

**Comment by tairt** [comment]
@silviapfeiffer I think that it is a grammar problem that makes syntax parsing difficult. I will try to explain this better with examples.

**Comment by silviapfeiffer** [comment]
@tairt please do - I don't follow where you see a problem

**Comment by silviapfeiffer** [comment]
@tairt ping

**Comment by tairt** [comment]
Sorry for the long silence. I expected a short discussion at TPAC and then failed to pick this up again.

I wanted to point out that instead of defining the syntax like this

```
C ::= A | B
A ::= "token1"*
B ::= "token2"
```
it may be clearer and easier to write grammar parsers if it is defined as follows:

```
C ::= A? | B
A ::= "token1"+
B ::= "token2"
```

But I think that it is not the goal of WebVTT Syntax to be transferred in a context free grammar or to be represented by EBNF. Parsing should be done by the parsing algorithm. 

I therefore close this issue and you may regard this comment as "won't fix" or "rejected". In any case I am fine with moving on and leave the spec as is.
