### ISSUE TITLE
Wide Review Comment 2017: Text color must be mandatory

### ISSUE THREAD

**Issue by tairt** [w3c/webvtt#365]
User agents that render WebVTT must support text color. As the conformance class "User agents that don’t support CSS" is mentioned, this type of user agent would currently not support text color (see also https://github.com/w3c/webvtt/pull/279 ).

**Comment by silviapfeiffer** [comment]
Is this a request to simply land #279 ?

**Comment by silviapfeiffer** [comment]
So, I went ahead and reused what Simon started in #279 but extended it for background colors (as discussed in #272 ).

This allowed me to add blue and black also as text color, but I added a warning to not use them with the default background. Note thats this follows what was discussed in https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html#cea-708-background-colour in the CG.

If we add this, we will also need to add new tests to the web platform tests.

**Comment by silviapfeiffer** [comment]
See the comments of @hober in the patch: it's true that we can right now sorry text color by adding classes to WebVTT files in the STYLE section. But we'd have to explain what CSS subpart needs to be supported in STYLE, including which colors and background. Would that be an acceptable alternative solution for this problem?

**Comment by tairt** [comment]
See comments in https://github.com/w3c/webvtt/pull/279

**Comment by silviapfeiffer** [comment]
applied requested changes to the patch, please review

**Comment by dwsinger** [comment]
Note that having c.bg_black available also applies to the arguments in #372

**Comment by dwsinger** [comment]
Am I missing where we say that all UAs should support the styles pre-defined in a style-sheet in an annex, and that annex? (The style sheet is the color-specific styles in the style-sheet in https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/608toVTT.html )

**Comment by silviapfeiffer** [comment]
I tried putting it in an Annex, but this is for authors and it will get lost there, which is why I moved it into the main text. We're not going to reference the other spec, since it's not standardised and this is not 608/708 specific.

I thought I had added a note that browsers should implenent this via a user agent style sheet...

**Comment by silviapfeiffer** [comment]
.. yes, I have!

**Comment by silviapfeiffer** [comment]
@tairt can you confirm that the landed patch in #395 satisfies your request? Thanks!

**Comment by tairt** [comment]
This issue can be closed. Thank you for the changes!
