### ISSUE TITLE
Wide Review Comment 2017: positioning with cue box vs region

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#376]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

Two positioning and sizing constructs are defined: the cue box and the region. It is not clear in the _data model_ section why both are needed and how a cue box is supposed to interact with a region. Indeed it appears that they are independent constructs given that only cue's position (and none of the other attributes) relates to or depends on the region. The cue box size is relative to the video viewport, not the region. This means that the concept of a region is not a "bounding box" within which cue text is rendered, but is only an alternative positioning reference. That semantic definition differs from other specifications that define regions, including TTWG's other specification covering this use case, TTML. (as Chair, I would prefer that there be semantic alignment here between the working group's specifications, and given the history and current state, that would mean modifying the treatment of regions in WebVTT.)

**Comment by silviapfeiffer** [comment]
The region is definitely a bounding box within which cues are rendered. I've clarified that in the patch.

About the cue box size: 4.4 explains that if the cue has a "vertical", "line" or "size" setting, the cue drops out of the region. Otherwise, the cue's width is calculated to be relative to the region width rather than the viewport. I've added some clarifying text.

**Comment by silviapfeiffer** [comment]
add this also to cue box explanation

**Comment by silviapfeiffer** [comment]
Please review this patch as well as the patch at #383

**Comment by nigelmegitt** [comment]
Noting that I approved the patches already, marking as commenter agreed.
