### ISSUE TITLE
Wide Review Comment 2017: line cue setting direction

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#382]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

(Context is section 4.4 "WebVTT cue settings" -> the "WebVTT line cue setting")

looking at that line cue setting, it "configures the offset of the cue box from the video viewport's edge in the direction opposite to the writing direction". I think that means "orthogonal to the writing direction" but it could be interpreted as the negative of the writing direction, i.e. If the writing direction is top-to-bottom then does this mean left-to-right or bottom-to-top? 

Then the WebVTT position cue setting "configures the indent position of the cue box in the direction orthogonal to the WebVTT line cue setting". Why doesn't it simply say "in the writing direction"?

**Comment by silviapfeiffer** [comment]
The writing direction is specified here: https://www.w3.org/TR/webvtt1/#webvtt-cue-writing-direction and it is either horizontal or vertical. The example provided should have clarified this, it says: For horizontal cues, this is the vertical offset from the top of the video viewport.

I'll change "opposite" to "orthogonal" and add some clarifying text.

**Comment by nigelmegitt** [comment]
Thanks, that looks good for the first part of the issue - there remains the question at the end.

**Comment by silviapfeiffer** [comment]
Resolution at TPAC: Silvia & Nigel to work out the last sentence

**Comment by silviapfeiffer** [comment]
About the last sentence:

The definition of "position" says the following:
The position defines the indent of the cue box in the direction defined by the writing direction.
https://w3c.github.io/webvtt/#webvtt-cue-position

So, what you are requesting is already defined as such.

The later explanation of "position" at
https://w3c.github.io/webvtt/#webvtt-position-cue-setting
just explains the relationship between "position" and "line" cue setting. It provides information in that given context.

I think this is ok as is.

**Comment by silviapfeiffer** [comment]
@nigelmegitt could you review and say if you're ok with the patch as landed in https://github.com/w3c/webvtt/pull/399 ?

**Comment by nigelmegitt** [comment]
#399 generated a couple of further questions for me. Plus it does not address the point about the language in the note under WebVTT position cue setting which still weirdly says "configures the indent position of the cue box in the direction orthogonal to the WebVTT line cue setting" rather than "configures the indent position of the cue box in the writing direction".

**Comment by silviapfeiffer** [comment]
That would be a repetition because that was already stated before in the definition of "position" (see https://github.com/w3c/webvtt/issues/382#issuecomment-343637820).

That note is not providing a definition - rather it is clarifying a different relationship. It's deliberately not repeating the definition.

**Comment by nigelmegitt** [comment]
OK, I still think it's weird, but I can live with it.

**Comment by silviapfeiffer** [comment]
Could you please choose an appropriate label (commenter-agreed or commenter-agreed-partial)? We can then close this issue. Thanks.

**Comment by dwsinger** [comment]
I chose for @nigelmegitt but he can change if he likes.

**Comment by nigelmegitt** [comment]
Seems like partial agreement is a better fit for this situation.
