### ISSUE TITLE
Wide Review Comment 2017: positioning model

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#383]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

It would be easier for me to understand and follow if there were a clearer box model, in which there is a region box, a cue box within that region, and then a set of cue lines within that cue box. Then the positioning units of, say, the cue box, can be in terms of lines, relative to the region edges, and the overall rendering area (the default region?) can be positioned relative to the video or the video viewport in a consistent manner.

**Comment by silviapfeiffer** [comment]
We can add some descriptive text to section 3 where the cue and region are introduced. Essentially it's as follows:

The box model of WebVTT consists of three elements: the video viewport, cues and regions. The video viewport is the rendering area into which cues and regions are rendered. Cues are boxes consisting of a set of cue lines. Regions are subareas of the view viewport that are used to group cues together. Cues are positioned either relative to the video viewport or relative to a region.

Would that be sufficient?

**Comment by dwsinger** [comment]
The box model of WebVTT consists of three elements: the video viewport, cues, and regions. The video viewport is the rendering area into which cues and regions are rendered. Cues are boxes consisting of a set of cue lines. Regions are subareas of the video viewport that are used to group cues together. Cues are positioned either relative to the video viewport or inside a region. Regions are positioned in the video viewport.

**Comment by silviapfeiffer** [comment]
Resolution at TPAC: Silvia to work with Nigel to resolve the wording - this is the right approach

**Comment by dwsinger** [comment]
(editors to finesse with the commenter. maybe put the text into encapsulation order, for clarity...)

**Comment by silviapfeiffer** [comment]
explain how the setting work on cues and regions and which are applied as group and single

**Comment by silviapfeiffer** [comment]
@nigelmegitt please review the PR

**Comment by nigelmegitt** [comment]
@silviapfeiffer done

**Comment by dwsinger** [comment]
added @nigelmegitt commenter-agreed and closing

**Comment by silviapfeiffer** [comment]
https://github.com/w3c/webvtt/pull/409 is the Telebart PR and it hasn't landed yet...

**Comment by nigelmegitt** [comment]
Also I haven't completed the (re-)review so this was too quick.

**Comment by silviapfeiffer** [comment]
#409 has landed
