### ISSUE TITLE
Wide Review Comment 2017: formatting issues

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/webvtt#385]
Copy/paste from https://lists.w3.org/Archives/Public/public-tt/2017Sep/0080.html - raising as an issue for tracking/disposition purposes.

There seem to be some formatting oddities when I view the specification on Firefox or Chrome – in section 3.1 there's an algorithm for calculating the computed line, whose outline box might be helpful but overlaps the bullet numbers on the left.

The diagram at the bottom of section 3.2 seems to truncate the word "Video viewport".

Some text has a yellow highlight colour without explanation, e.g. In Example 19.

**Comment by silviapfeiffer** [comment]
The yellow highlight colour on srclang in Example 19 is to highlight the srclang attribute use in that example. I think it's useful. The text above it says:

The applicable language for the list of WebVTT Node Objects can be set by the srclang attribute in HTML.

So it makes sense to mark the srclang attribute specifically. I'll not change this in the patch, if that's ok with you.

**Comment by nigelmegitt** [comment]
@silviapfeiffer Oh I see, that wasn't obvious to me. I see what you mean, but it does still seem odd that it's the only fragment of an example that warrants this yellow styling.

**Comment by silviapfeiffer** [comment]
Resolution: remove the yellow

**Comment by silviapfeiffer** [comment]
Highlight was removed and patch updated, please review.

**Comment by silviapfeiffer** [comment]
Patch landed, all issues were addressed. I think we need issue submitter comment.

**Comment by silviapfeiffer** [comment]
@nigelmegitt are you ok with the resolution of this issue with the patch in https://github.com/w3c/webvtt/pull/396 ?

**Comment by nigelmegitt** [comment]
For posterity: https://github.com/w3c/webvtt/pull/396#pullrequestreview-78745850
