### ISSUE TITLE
voice attribute is either voice, title or a "value" attribute

### ISSUE THREAD

**Issue by fcartegnie** [w3c/webvtt#401]
stylesheets example 8, css attribute selector is "voice"
```
::cue(v[voice="Esme"]) { color: cyan }
::cue(v[voice="Mary"]) { color: lime }
```

From Definitions, object "value" (go figure, as this is defined as span below) is name of voice
> WebVTT Voice Objects
> 
>     These represent spans of text associated with a specific voice (a WebVTT cue voice span) in WebVTT cue text. A WebVTT Voice Object has a value, which is the name of the voice.
> 

From DOM constructions rules, attribute is "title"

> WebVTT Voice Object | HTML span element with a title attribute set to    the WebVTT Voice Object’s value.
> -- | --
>

**Comment by fsoder** [comment]
https://w3c.github.io/webvtt/#cue-selector

> For the purposes of attribute selector matching, WebVTT Internal Node Objects have no attributes, except for WebVTT Voice Objects, which have a single attribute named "voice" whose value is the value of the WebVTT Voice Object...

**Comment by silviapfeiffer** [comment]
DOM construction is what happens in the browser to resolve the WebVTT file. You only use the "voice" attribute in ::cue CSS selectors.

The mapping to "title" is just what happens in browser behind the scenes - don't look there for authoring advice. And "value" in that context just says that the title attribute's value is set to the text of the "voice" attribute. I.e. behind the scenes,  a browser converts  `::cue(v[voice="Esme"])` to `<span title="Esme">` in their shadow DOM. As a WebVTT author, you don't have to worry about this.
