### ISSUE TITLE
::cue and ::cue-region pseudo selectors shouldn't allow selectors

### ISSUE THREAD

**Issue by fcartegnie** [w3c/webvtt#404]
Seems to break most grammar rules when a selector is used as peuso-element expression.

confirmed on Firefox
https://developer.mozilla.org/fr/docs/Web/CSS/::cue

> . Firefox currently does not support a parameter on ::cue

::cue(b)
is equivalent to
::cue b

**Comment by fsoder** [comment]
I'm not quite sure what you mean by "break most grammar rules". (Not sure what relevance it has that Gecko does not implement this - other UAs have - so "confirming" anything on Gecko seems odd.)

**Comment by fcartegnie** [comment]
ex
::cue(b)
is a function which is a pseudo selector by : prefix,
so b is string or ident term in its expression.
https://www.w3.org/TR/2003/WD-css3-syntax-20030813/#grammar0

which means ::cue(v b), ::cue(v c.foobar) can't be valid, because these are selectors, thus, not a valid expr

**Comment by fsoder** [comment]
WebVTT defines the ::cue() functional pseudo-element to take a selector argument [1]. The CSS selectors spec (as referenced by WebVTT) is probably better to look at for selector issues/syntax [2].

[1] https://w3c.github.io/webvtt/#cue-selector
[2] https://drafts.csswg.org/selectors-4/#grammar

**Comment by silviapfeiffer** [comment]
Firefox does not implement ::cue(b) yet. CSS deals just fine with a functional pseudo-element as @fsoder explained.
