### ISSUE TITLE
Throw exception when setting region id "-->" ?

### ISSUE THREAD

**Issue by bechen** [w3c/webvtt#405]
Hi all, I'm implementing  region id attribute for firefox.
https://w3c.github.io/webvtt/#dom-vttregion-id
https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/region.html#webvtt-region-identifier

It says region id doesn't allow "-->" substring, so on setter, should we throw or just set it to null string?

**Comment by fsoder** [comment]
You should set it to the string "-->"?

**Comment by bechen** [comment]
https://dvcs.w3.org/hg/text-tracks/raw-file/default/608toVTT/region.html#webvtt-region-identifier
" The string must not contain the substring "-->" "
So what UA should do if the string contain "-->"?

**Comment by fsoder** [comment]
AFAIK, that's only a parsing restriction. Setting "-->" on a VTTRegion needn't care about it. (Post parsing, the region id is only for CSS matching.)

(Also, you should probably be looking at https://w3c.github.io/webvtt/#regions and not the link above.)

**Comment by silviapfeiffer** [comment]
The parsing is specified in the spec - you just need to follow it. It's an authoring error when a --> is included, but you can pretty much ignore that. Just follow the parsing specification and the result will fall out.

**Comment by silviapfeiffer** [comment]
Also, what @fsoder said. :-)
