### ISSUE TITLE
:future pseudo class unclear

### ISSUE THREAD

**Issue by fcartegnie** [w3c/webvtt#406]
:future pseudo class usage is obscure.

To me there's an unmentioned "visibility" property on Timestamp Objects that can be changed, 
and this needs to be considered when selecting content at rendering time,
so css declaration has visible effect on those nodes in the future.

**Comment by silviapfeiffer** [comment]
The :future pseudo-class is also defined in CSS: https://drafts.csswg.org/selectors-4/#the-future-pseudo . It's just a selector which selects based on time. You can thus change the "visibility" property based on time using ::cue .

See the example in the spec:

> video::cue(:future) {
>   color: cyan;
> }

I don't see how there's anything unclear. Can you explain?

**Comment by fcartegnie** [comment]
According to the "processing model",
"cues" is filled with active cues, which are defined by their timestamp.
Then css is applied to this list, altering their visibility: add / remove in cues. 
I don't see how future nodes visibility can be changed then. Since they are not in the "cues" they can't be switched to visible/added.

I don't even see how that could even work when using samples mapping (ex: mkv), but that's an issue outside that spec.

**Comment by dwsinger** [comment]
> On Dec 3, 2017, at 3:21 , François Cartegnie <notifications@github.com> wrote:
> 
> According to the "processing model",
> "cues" is filled with active cues, which are defined by their timestamp.
> Then css is applied to this list, altering their visibility: add / remove in cues.
> I don't see how future nodes visibility can be changed then. Since they are not in the "cues" they can't be switched to visible/added.

Right, but there can be future text in nodes;  have a look at the Karaoke example

<https://www.w3.org/wiki/VTT_Concepts#Timestamp_Tags_.28Karaoke_Style_and_Paint_On_Caption_Text.29>

does that help?

> 
> I don't even see how that could even work when using samples mapping (ex: mkv), but that's an issue outside that spec.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

David Singer
Manager, Software Standards, Apple Inc.

**Comment by dwsinger** [comment]
@fcartegnie does the above help clarify?

**Comment by fcartegnie** [comment]
The pointed example still does not change or implies visibility attribute change on those timestamps objects

**Comment by dwsinger** [comment]
So given this cue:
00:00:18.500 --> 00:00:20.500
Like a <00:19.000>big-a <00:19.500>pizza <00:20.000>pie

at time 18.50, "Like a " is current, and "big-a " "pizza " and "pie" are all ::future. as time advances they change from being future. Is this not clear

**Comment by fcartegnie** [comment]
> at time 18.50, "Like a " is current, and "big-a " "pizza " and "pie" are all ::future
and then
```
::cue:future {
  text-shadow: black 0 0 1px;
}

```
is applied. But since they are in "future" they are still "hidden", so that's pointless.
hence my question about visibility property change

**Comment by dwsinger** [comment]
OK, I am not a Karaoke expert. But my understanding is that this cue is not "hidden" after time 18.5, the entire cue is in the rendering tree, and aspects of it are ::future. Maybe tell us why you feel those cue-parts are "hidden"? I think they are visible and styling is controlled by ::future.

**Comment by fcartegnie** [comment]
So you mean timestamps objects nodes are never filtered at rendering time, and the whole cue is always visible, regardless of playback position ?

**Comment by dwsinger** [comment]
No, there is a set of active cues (the current time is within the range of their start and end times). future and past apply to times within those, as I understand.

**Comment by fcartegnie** [comment]
> No, there is a set of active cues (the current time is within the range of their start and end times). future and past apply to times within those, as I understand.

We already figured out above that the future and past cannot work across cues.
Reformulating my previous comment:
(for playback time inside cue range)
- timestamps have no effect on rendering and any timestamp'ed content is always displayed.
- timestamps only purpose is :future and :past usage (*)

(*) which also would mean this standard is pretty bad for converted popon closed captions, if there's no css or future/past support

**Comment by dwsinger** [comment]
that's roughly my understanding, yes.

**Comment by dwsinger** [comment]
mind you, you can *emulate* paint-on captions by setting the :future styling so that the characters are invisible, and by putting a timestamp on every character. But paint-on is not, IMHO, desirable from the user's point of view, it enabled captions to be painted as captioners typed, in old real-time systems.

@fcartegnie Can we close this as 'works for me' now you get what :future is for?

**Comment by fcartegnie** [comment]
that's impl in vlc (as far as we can do as we have no dom rendering engine)
