### ISSUE TITLE
Suggest edits to the "cue overlap avoidance" portion of the specification

### ISSUE THREAD

**Issue by guohuideng** [w3c/webvtt#441]
under session 6.1,  under clause
"If cue’s WebVTT cue snap-to-lines flag is false", the "step 4" deals with cue overlap/cutoff avoidance. below is the text from the specification.

"If there is a position to which the boxes in boxes can be moved while maintaining the relative positions of the boxes in boxes to each other such that none of the boxes in boxes would overlap any of the boxes in output, and all the boxes in boxes would be within the video’s rendering area, then move the boxes in boxes to the closest such position to their current position, and then jump to the step labeled done positioning below. If there are multiple such positions that are equidistant from their current position, use the highest one amongst them; if there are several at that height, then use the leftmost one amongst them."

////
The text has a few problems. 1. it's vague and it could be more concise. 2. it actually only suggests actions on "cut off" case, but not the case of cues overlapping with one another. 3. It could state "video safe area" instead of "rendering area". because of overscan the cue can still be cut off if placed too close to the boundary. Therefore it is common practice to put the cue in "save area".4. it put too much restricts on how the feature should be implemented. The specification should define syntax and semantics of the webvtt, and leave spaces to developers to improve the functionality.

Therefore my suggestion is to replace the text above with something like the below.
"
If the cues placement suffers from one or more problems listed here, then efforts could be made to mitigate or eliminate such problem(s)  by moving some cue boxes or all the cue boxes: 1. Any cue box is not placed in video safe area 2. Two or even more cue boxes overlap each other (one another).
"

/// With such text in specification, developers can also implement the feature incrementally, or keep improving this feature in the future.

**Comment by silviapfeiffer** [comment]
About your issues and suggested solution:

1. It's vague: your proposal is to replace a somewhat vague but concise description of what to do with the boxes with a specification that is even vaguer and says nothing at all about what to do with the boxes.

2. Only refers to cut-off problem: that's incorrect, it includes "such that none of the boxes in boxes would overlap any of the boxes in output" - it clearly talks about overlapping cues.

3. Doesn't deal with overscan: that's correct and it's on purpose. Overscan used to be dealt with separately, but got removed recently because implementers didn't think it was necessary in the modern age any more, see https://github.com/w3c/webvtt/issues/379. I don't believe browsers actually know the "video safe area" when they render but I could be convinced to change this. @eric-carlson , @foolip I'd be curious to hear your comments on this.

4. Freedom to developers: there already is sufficient freedom for developers on how to implement this - I think your suggested text is essentially the same as the current one except it doesn't talk about retaining the relative order of the boxes and keeping proximity.

**Comment by guohuideng** [comment]
Hi silviapfeiffer
Thank you for you quick response!

about 1.2, sorry my bad, it does refers to cut-off problem. Also "vague" is a wrong word I used. However I am a bit uncomfortable with "If there are multiple such positions that are equidistant from their current position, use the highest one among them; if there are several at that height, then use the leftmost one amongst them." (see below section 4.)
///////////
3
I still believe cut-off problem  from overscan exists. We already have the issue of cut off because of overscan. Also, if the cue is right at the boundary, it doesn't look good. 
The "safe area" can be an area that's reasonably slightly smaller than the video rendering area.
4.
yes that's I meant. I actually agree with "relative order" and "proximity" in princible, although I don't expect that to be in specification. Those are principles that should be allowed to break in certain situations. 
/////// quote
"If there are multiple such positions that are equidistant from their current position, use the highest one amongst them; if there are several at that height, then use the leftmost one amongst them."
//////////////
The reason I think it's too restrictive:
1. The rules above doesn't give good result in some cases. For example, if there are two cues, on the same line, but overlap by one letter. The rules above would suggest raise the one on the left by one letter. But a good solution is to separate them further if there are enough space

2. Cue boxes overlapping can be complicated, there can be more than 2 cue boxes overlapping. In that case the implementer should have freedom to move the box in a way that requires less effort. It could be preferable to move one box a litter further rather than move more boxes sticking to "minimal movement + max height" principle.

3. With a looser text, one can submit a patch to the webvtt renderer engine that immediately improve the output (fix some common problems) while being completely compatible to the webvtt specification, and have the space later to further improve the cue box overlap-cutoff avoidance mechanism.  Note, when the cue is cut off, or overlapped, it's considered "broken", and any fix would be better than no fix at all. In future more effort can be made to improve how the cue placement should be adjusted to achieve 1. best aesthetics 2. least computing cost

**Comment by silviapfeiffer** [comment]
About overscan: we had defined a "save area" for that before but no browser implemented it. So we removed it. If you're proposing such a change, we need to get all the browsers on board with it.

So, you're suggesting to remove "If there are multiple such positions that are equidistant from their current position, use the highest one amongst them; if there are several at that height, then use the leftmost one amongst them." ? I could live with that, but want to hear opinions of others.

**Comment by guohuideng** [comment]
Hi silviapfeiffer, I asked for input in another thread in chromium so hopefully we can hear from them soon.

It would be great if the two (overscan and taking away the "if there are ...") can be done.

**Comment by guohuideng** [comment]
Another thought:

I think this portion of specification could be "optional". (that why I suggest "... efforts Can be made to.. .") Right now the chromium project didn't implement it and I am planing to implement it.

Therefore in the case of overscan, it is still fine if any browser doesn't implement. What we need is too allow (slight adjustment) if the cue is way too close to the boundary.

**Comment by fsoder** [comment]
About the "A or B?" issue, this would be defined by the rendering steps, and I believe it should essentially mean that whichever cue is first in cue-order will keep its position, while any later ones will need to "avoid overlap" (pretty sure we had test for this for the old spec text - which didn't differ that much in this case.)
Having undefined behavior in the/a spec in general isn't a great idea, since it leads to unpredictability for authors. Hence it's better to suggest tweaks to the specified heuristics (like the overscan area.)
As for not to "put them touching each other" it seems like a highly subjective thing, and not aiming for "as close as possible to the specified position" (which I've always interpreted the intent of the spec as being.)

**Comment by guohuideng** [comment]
Hi fsoder, so are you suggesting that the range (or size) of "safe area" should be defined in the specification?

Thanks a lot.

**Comment by fsoder** [comment]
I think the spec would only define it as a variable or sorts (UA specific.) IIRC, there used to be allowance for a UA-defined 'margin' that inset the rendering area for the rendering steps. (I believe Blink has that 'margin' implemented as a setting still.)

**Comment by guohuideng** [comment]
I saw the "margin" is used in the "snap-to-line == true" in the chromium source code.
But I am not able to find it in the spec

Is the below the right link to the latest version of the spec?
https://w3c.github.io/webvtt/#processing-model

I am proposing a minimal of such "margin value". the reason is we need to deal with some very rare but still important source that has wrong settings, so the cue is touching the video rendering border that the text is cut of on some TV(due to over scan)

So we need to be allowed to put a "minimal margin".  For example, if the cue is touching the bounder of video rendering area, we need to be able to fix it by moving the cues into the center so the text won't be cut off on some TV.

This is needed on both "snap-to-line == true/false" case, and the margin needs to be in both horizonal and vertical.

**Comment by fsoder** [comment]
The 'edge margin' was removed from the spec (in https://github.com/w3c/webvtt/commit/6f73c35e7c70c90592cbb6468e75afe4248dfca2 it seems, in response to a wide review comment it seems), which is why you can't find it in the current version.

**Comment by guohuideng** [comment]
Hi fsoder,
Thanks a lot for clarification. 
So what do you guys suggest so that I could move the cue off the boundary of the video rendering area? (in both the snap-to-line==true/false case)

**Comment by fsoder** [comment]
You could probably start by prototyping an implementation in Blink (using the infrastructure that already there.) It would seem that from a spec PoV there would need to exist a mechanism to allow the 'edge margin' to be forced to zero (i.e turn it off.)

**Comment by silviapfeiffer** [comment]
The spec has removed the the edge margin because all browser implementations had it set to 0.

**Comment by guohuideng** [comment]
Hi, 
I looked into Blink. The "margin" appears to only apply to the "snap_to_line==true" case, and it only apply to the side, not the top&bottom?

fsdoer: I am confused here. I thought I need to enforce a "minimal"  margin (this margin applies to both the sides and top/bottom), instead of "force to zero"? Can you please be more detailed about the "forced to zero idea"?

What I'd like to do is: if the cue is way to close to any boundary (like touching, or even being cut off) but there is significant space on the direction, I will move all the cues together to the other direction so there is a little space between the cue boxes and the closest boundary.

I'd like to work with you guys to achieve an agreement which I can implemenet in Blink. 

Thanks.

**Comment by guohuideng** [comment]
I have some resources where the cue either 1. being cut off at the bottom or 2.touching the left edge and thus being cut off on some TV.

I can leave off the overlapping  avoidance for now since the cut off problem is more urgent to me.
////////////////////////////////
I wonder if you guys can let me add the following logic into Blink:

(at the very last step of LayoutUpdate() )
if the cue box is touching a boundary (or being cut off), but there is plenty space on the other side
==> let me move all the cue boxes for a small distance

**Comment by guohuideng** [comment]
Hi fsoder,

Yes you are right. It is ChromeCast again :) 

I think that implementing behind a flag is a great idea. (much cleaner and it can be separated from the rest of the issues) 

My urgent need is to put in a "salvage" function to catch cut-off (snap-to-line==false only) and touching-boundary cases. So I put a flag such that the salvage  function is not called unless the blink is compiled for Chromecast.

Thank you very much for you guys help! If you guys have any concerns please let me know.

**Comment by silviapfeiffer** [comment]
If you have any examples of problematic files, would you be able to share them so we can discuss with more context? I.e. share the WebVTT file (extract) and a couple of screenshots on how it's rendered? That would really help with the specification update. I'm still unclear what you're trying to do that's not allowed by the spec.

**Comment by guohuideng** [comment]
Hi silviapfeiffer,

The one that I ask for additional permission (i.e., not allowed by current spec) is that, I like to the text to be located within "title safe area", if the area is big enough to display the text. (which is usually the case)

This will only apply to a very rare cases where the text is set to start from left boundary of the screen.

The reason is that Chromecast uses TVs as output device, so there must be a "forced margin" between the text and the boundary of the monitor. Otherwise on some TV the text would be cut off.

**Comment by guohuideng** [comment]
I don't have those TV here so I couldn't produce the problem and take a picture. But we have been reported the issues happen. So hopefully after I add the logic they will tell me the problem is solved.

Thanks.

**Comment by silviapfeiffer** [comment]
Could you open a new bug about "definition of a title safe area for overscan" and explain why it is a problem, who is having this problem and how it is a problem for the Web? Thanks.

**Comment by guohuideng** [comment]
Hi silviapfeiffer,

Done. It's here https://github.com/w3c/webvtt/issues/442

Thank you.

**Comment by robwalch** [comment]
One of the issues I've seen in existing implementation is that the vertical order of lines will get changed to avoid overlapping. The result is that the copy because difficult to read since it's not presented in the order intended. Do these changes take that into consideration?

**Comment by guohuideng** [comment]
Hi robwalch,

So I am working on a "title safe area display" adjustment but that will only affect Chromecast. However you will be able to see the code within Chromium Blink 

This adjustment won't have anything to do with the way the cue box is moved to avoid overlapping.

When the cues are overlapped and movement is required to avoid the overlapping, it is very difficult if possible to guarantee a good re-arrangement for any input.

I think what described in the spec is a simple and effective way to achieve decent result. I suggested taking it off so the implementer can further improve it if they can, but it looks like it is important to most of the people that the implementation is consistent across all browsers so that the spec define exactly what to do about overlapping.

**Comment by robwalch** [comment]
Thanks @guohuideng! Sorry if my question is misplaced here. I appreciate the response.

**Comment by guohuideng** [comment]
You are welcome robwalch.

**Comment by guohuideng** [comment]
Hi guys, I am looking at the layout_vtt_cue.cc in chromium project. I notice that the blink is using LayoutBox returned from CueBoundingBox(...) to determine the area that the cue would occupy. Thus it judges if two cue boxes would overlap by looking at if the two LayoutBox would overlap.

However I noticed that this LayoutBox may be significantly larger than the actual size of the text. For example, when the text write mode is "from left to right", and the text is very short but the "size" value ended up as "100%" the cue box is still considered as long as the width of the entire video. In fact I think the LayoutBox's "width" is the same as "size", not actual length of the test.

So I wonder if there is a way to get to know the real "size" of those cue boxes. (the actual space the text would occupy)

Thanks for reading and helping. iI really appreciate it,

**Comment by guohuideng** [comment]
Hi guys, thanks for the help. I found out unless I can "shrink" the layout box to true length of the text I shouldn't move the text along the write-direction. therefore I think that's too much to do. We will ask content provider to correct the overscan on the side issue.

However I still like to put a custom "layout adjuster" for us so we have a little border on the bottom. I also like to put a custom "overlap avoidance" there which takes affect until the "overlap avoidance" per the spec is implemented. 

Again I will flag this custom "layout adjuster" so that it is only active when compiled to Chromecast

**Comment by guohuideng** [comment]
BTW, silviapfeiffer and fsoder:

regarding the overlap avoidance procedure by the spec, it is still unclear if it implies  the "snap-to-line==false" should be handled similarly to "snap-to-line==true". If yes, I see a problem: suppose line 1 and line 2(line 2 is supposed to be under line 1) don't overlap, but line 2 is cut off at the bottom. the algorithm will skip line 1 and move line 2 on top of line 1, which gives bad result. In fact it is better to first address the overlap problem, then move all the boxes (while keeping their relative position) if they are cut off by the border.

Also I think it is easier just to raise the cues. (like the case snap-to-line==true)
////////

Since I will have to leave bottom margin a little mine won't be able be qualify as "universal" so the implementation I am going to do will only be active for our own product. In case you guys think some of the idea will be beneficial that would be great

Thanks again for reading and helping

**Comment by guohuideng** [comment]
Surprise surprise... I found out the latest blink now properly played the problematic subtitles now. It was broken (text touching the bottom and even being cut off) a few month ago, so I don't need to do anything now. Those material has "snap-to-line" set to "false"

I wonder what recent change in the blink fixed the problem...

**Comment by silviapfeiffer** [comment]
OK, so can we just close this issue?

**Comment by guohuideng** [comment]
Hi silviapfeiffer
Yes, I am closing the issue, thank you again!
