### ISSUE TITLE
Video-internal tracks

### ISSUE THREAD

**Issue by andrewbaxter** [w3c/webvtt#524]
The current specification only discusses external subtitle tracks, but the webm container (and others) explicitly supports embedding webvtt data within the container file.  Across the web there have been various questions about how to play video with embedded webvtt data, and the answers are basically "it's not allowed", but aside from not being mentioned or implemented I couldn't find a reason.

I'm not sure if this was discussed before (I did google a decent amount, and searched this repo), or if the choice to only have external vtt tracks was technical or something else, but if it hasn't already been requested I'd like to formally request it now. I believe this is the relevant specification for the `<track>` element, which AFAIK would be the best place for this discussion, but let me know if there's somewhere else I should go.

My reason for wanting this is mainly that coordinating the management of multiple files is much more difficult than a single file operationally -- transferring, storing the files together and not separating them, preventing mixups, cleaning up related files, extra steps to extract already-embedded vtt tracks, etc -- so being able to bundle it would be a great help.

**Comment by eric-carlson** [comment]
This is not a spec issue as the HTML spec defines [rules for sourcing in-band text tracks](https://html.spec.whatwg.org/#sourcing-in-band-text-tracks).

Apple's WebKit port added support for in-band text tracks [in 2012](https://bugs.webkit.org/show_bug.cgi?id=103663), but as far as I know none of the other major browsers supports this feature.

**Comment by andrewbaxter** [comment]
Ah thanks! That was probably the terminology I was missing.

For reference,

Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=882675

Chromium: https://issues.chromium.org/issues/40568976 indicates it _was_ (partially, with a gate?) implemented and argues for removing it because no sites decided to rely on incomplete/hidden functionality (?).  It seems like it may have been deleted in a separate task here: https://issues.chromium.org/issues/40278255
